### ISSUE TITLE
Scrollbar area contains white-on-white scrollbar in light theme 

### ISSUE THREAD

**Issue by Esgariot** [nealmckee/penumbra_vscode#5]
<img width="131" alt="image" src="https://user-images.githubusercontent.com/6072243/183391952-5d2bc37c-81f3-4d52-a096-db53e508dcf0.png">

scrollbar breaks an otherwise nice looking composition of colors on different elements

**Comment by nealmckee** [comment]
Should be fixed with the newest version. Since the light theme is based on the dark one, it was just missing an inversion of color relationships here.
The new color for an inactive scrollbar handle is now the same as it’s overall shadow — I don’t think that this will cause issues but let me know if it does.
